config/routes.rb
Calender::Application.routes.draw do
  get "sessions/new"
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :events do
    resources :comments
  end

  root 'sessions#new'
  get 'edit_profile' => 'users#show'
  get 'sign_up' => 'users#new'
  get 'sign_in' => 'sessions#new'
  get 'sign_out' => 'sessions#destory'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :event
	belongs_to :user

	validates :event_id, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :comments
	has_many :users, through: :comments

	validates :title, presence: true
	validates :allDay, presence: true

	scope :between, lambda {|start_time, end_time| {:conditions => ["? < 
     ?", Event.format_date(start_time), Event.format_date(end_time)] } }

	def self.format_date(date_time)
      Time.at(date_time.to_i).to_formatted_s(:db)
    end

    def as_json(option = {})
      {
        :id => self.id,
        :title => self.title,
        :description => self.description || "",
        :start => starts_at.rfc822,
        :end => ends_at.rfc822,
        :allDay => self.all_day,
        :recuring => false,
        :url => Rails.application.routes.url_helpers.event_path(id),
      }
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :events, through: :comments
	has_secure_password

	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, uniqueness: true
	validates :name, presence: true
	attr_accessor :terms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authorize
  	if current_user.nil?
  		session[:protected_page] = request.fullpath
  		redirect_to sign_in_url, notice: 'You must login to view this page.'
  	end
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def login(user)
  	reset_session
  	session[:user_id] = user.id
  end

  def logout
  	reset_session
  	session[:user_id] = nil
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_event 
	#before_action :set_user
	before_action :set_comment, only: [:show, :edit, :update, :destroy]

	def index
		@comments = @event.comments
	end

	def new
		@comment = @event.comments.new
	end

	def create
		@comment = @event.comments.build(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to event_path(@event), notice: 'Comment made!'
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @comment.update_attributes(comment_params)
			redirect_to event_path(@event), notice: 'Comment updated'
		else
			render :edit
		end
	end

	def destroy
		@comment.destroy
		redirect_to event_path(@event), notice: 'Comment deleted!'
	end


private
	
	#def set_user
	#	@user = User.find(params[:user_id])
	#end

	def set_event
		@event = Event.find(params[:event_id])
	end

	def set_comment
		@comment = @event.comments.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:contents)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  
  def index
  	@events = Event.scoped
    @events = Event.between(params[:start], params[:end]) 
    if (params[:start] && params[:end])
      respond_to |format|
        format.html # index.html.erb
        format.json { render :json => events }
    end
  end

  def new
  	@event = Event.new
  end

  def show
  end

  def destroy
  	@event.destroy
  	redirect_to events_path, notice: 'Event Deleted'
  end

  def update
  	respond_to do |format|
  		if @event.update(event_params)
  			format.html { redirect_to @event, notice: 'Your event has been updated succesfully' }
  		else
  			format.html { render action: 'edit' }
  		end
  	end
  end

  def edit
  end

  def create
  	@event = Event.new(event_params)
  	if @event.save
  		redirect_to @event, notice: 'Your event was created'
  	else
  		render 'new'
  	end
  end

  private
  	def set_event
  		@event = Event.find(params[:id])
  	end

  	def event_params
  		params.require(:event).permit(:title, :description, :start, :end, :allDay)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		redirect_path = events_path
  		if session[:protected_page]
  			redirect_path = session[:protected_page]
  			session[:protected_page] = nil
  		end
  		login(user)
  		redirect_to redirect_path, notice: 'Logged In'
  	else
  		redirect_to sign_in_path, alert: 'Invalid Email/Password'
  	end
  end

  def destory
    logout
    redirect_to root_path, notice: 'Logged Out'
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params);
		if @user.save
			login(@user)
			redirect_to events_path, notice: "Thank you for signing up!"
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to root_path, notice: 'Account updated'
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		logout
		redirect_to root_path, notice: 'Account Deleted'
	end

	private
		def set_user
	  		@user = current_user
	  	end

		def user_params
			params.require(:user).permit(:name,:email,:password,:password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
	def self.included(base)
	    ActionView::Base.default_form_builder = StandardBuilder
	end

	class StandardBuilder < ActionView::Helpers::FormBuilder
		def error_messages(options = {})
			return unless object.respond_to?(:errors) && object.errors.any?

			if options[:error_message].nil?  
				errors_title = @template.content_tag(:h3, "Please fix the following errors:", class: "error-title")
			else
				errors_title = @template.content_tag(:h3, options[:error_message], class: "error-title")
			end
			errors_list = ""
			errors_list << object.errors.full_messages.map { |message| @template.content_tag(:li, message) }.join("\n")

			error_messages = @template.content_tag(:ul, errors_list.html_safe, class: "error-messages")

			@template.content_tag(:div, errors_title+error_messages, class: "form-errors")
		end

	end
end

app/helpers/layout_helper.rb
module LayoutHelper
	def title(page_title, show_title = true)
		content_for(:title) { page_title.to_s }
		@show_title = show_title
	end

	def show_title?
		@show_title
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p><%= comment.contents %></p>
	<p>
		<%= link_to 'Edit', edit_event_comment_path(@event,comment) %> |
		<%= link_to 'Delete', event_comment_path(@event,comment), method: :delete, confirm: 'Are you sua?' %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@event, @comment] do |f| %>
	<%= f.error_messages %>
	<%= f.label :contents %>
	<%= f.text_field :contents %><br>
	<%= f.submit  "Done" %>
<% end %>

app/views/comments/edit.html.erb
<% title 'Update Comment' %>

<%= render 'form' %>

<%= link_to 'Back', event_path(@event) %>

app/views/comments/index.html.erb
<% title @event.name %>

<h2>Comments</h2>

<%= render @comments %>

<%= link_to 'New Comment', new_event_comment_path(@event) %> |
<%= link_to 'All Events', events_path %>

app/views/comments/new.html.erb
<% title "New Comment for #{@event.name}" %>

<%= render 'form' %>
<br>
<%= link_to 'Back', event_path(@event) %>

app/views/events/_event.html.erb
<%= div_for event do %>
	<h2> <%= link_to_unless_current event.title, event_path(event) %></h2>
	<p><strong>Title:</strong> <%= event.title %></p>
	<p><strong>Start:</strong> <%= event.start %></p>
	<p><strong>End:</strong> <%= event.end %></p>
	<p>
			<%= link_to 'Edit', edit_event_path(event) %> |
			<%= link_to 'Comment', new_event_comment_path(event) %> |
			<%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: 'Really are you sua?' } %>
	</p>
<% end %>

app/views/events/_form.html.erb
<div class="well form-horizontal">
<%= bootstrap_form_for @event do |f| %>
	<%= f.alert_message "Oops got some errors" %>
	<%= f.text_field :title, label: 'Title', class: 'col-sm-3' %>
	<%= f.text_area :description,rows: '3' %>
	<%= f.form_group do %>
		<%= f.label 'Start:' %>
		<%= f.datetime_select :start_at %>
	<% end %>
	<%= f.label 'End' %>
	<%= f.datetime_select :end_at %>
	<%= f.form_group :allDay, label: { text: "Would you like it all day?" } do %>
		<%= f.radio_button :allDay, 1, label: "Yes" %>
		<%= f.radio_button :allDay, 0, label: "No" %>
	<% end %>
	<%= f.form_group do %>
		<%= f.submit 'Submit', class: 'btn btn-primary' %>
	<% end %>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<p><%= link_to 'Home', events_path %> -- >
Edit: <%= @event.title %></p>
<br>

<%= render 'form' %>

<br>
<% link_to 'Show', @event %>

app/views/events/index.html.erb
<h1>List of Events</h1>
<% if notice %>
	<p class="noticeLink"><%= notice %></p>
<% end %>

<%= link_to 'Create New Event', new_event_path %>
<br>
<div id='calendar'></div>

<%= render @events %>

app/views/events/new.html.erb
<h1>Create New Event yay!</h1>

<%= link_to 'Home', events_path %> --> New Event

<%= render 'form' %>

app/views/events/show.html.erb
<%= link_to 'Home', events_path %> -->
<%= link_to 'Edit', edit_event_path(@event) %>

<% title @event.title %>

<%= render @event %>

<br>
<h3>Comments</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if !current_user %>
        <%= link_to 'Home', sign_in_path, class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'Home/Events', events_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if current_user %>
    <%= link_to 'Profile', edit_profile_path, class: 'navbar-brand' %>
    <%= link_to 'Sign Out', sign_out_path, class: 'navbar-brand' %>
    <% else %>
    <%= link_to 'Sign Up', sign_up_path, class: 'navbar-brand' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Calender" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Calender" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/index.html.erb
<% title 'Staying on top of things' %>

<div class="homepage">

</div>

app/views/users/_formuser.html.erb
<div class="jumbotron">
	<legend>Register an Account</legend>
	<%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
		<%= f.alert_message "Oops got some errors" %>
		<%= f.text_field :name, label: "Username:", placeholder: 'Username' %>
		<%= f.text_field :email, label: "Email", placeholder: 'Email' %>
		<%= f.password_field :password, label: "Password", placeholder: 'Password' %>
		<%= f.password_field :password_confirmation, label: "Confirm Password", placeholder: 'Confirmation' %>
			<div class="form-group">
				<%= f.submit 'Submit', class: 'btn btn-primary'%>
			</div>
	<% end %>
</div>

app/views/users/_user.html.erb
<%= div_for user do %>
	<h2> <%= link_to_unless_current user.name, event_path(user) %></h2>
	<p><strong>Username:</strong> <%= user.name %></p>
	<p><strong>Email:</strong> <%= user.email %></p>
	<p>
			<%= link_to 'Edit', edit_user_path(user) %> |
			<%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Really are you sua?' } %>
	</p>
<% end %>

app/views/users/edit.html.erb
<% title 'Update Account' %>

<%= render 'formuser' %>

app/views/users/new.html.erb
<% title 'Sign Up' %>

<%= render 'formuser' %>

app/views/users/show.html.erb
<% title "Account: #{@user.name}" %>

<%= render @user %>